///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MovieModel {
/*
{
  "title": "After Dark in Central Park",
  "year": 1900,
  "cast": [
    "Rex Harrison"
  ],
  "genres": [
    "Drama"
  ]
}
*/

  String? title;
  int? year;
  List<String?>? cast;
  List<String?>? genres;

  MovieModel({
    this.title,
    this.year,
    this.cast,
    this.genres,
  });
  MovieModel.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    year = int.tryParse(json['year']?.toString() ?? '');
    if (json['cast'] != null && (json['cast'] is List)) {
      final v = json['cast'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      cast = arr0;
    }
    if (json['genres'] != null && (json['genres'] is List)) {
      final v = json['genres'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      genres = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['year'] = year;
    if (cast != null) {
      final v = cast;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['cast'] = arr0;
    }
    if (genres != null) {
      final v = genres;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['genres'] = arr0;
    }
    return data;
  }
}
